# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 11:50
from __future__ import unicode_literals

import core.django_ext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='asset_wechat_media_id',
            field=models.CharField(blank=True, db_column='c_asset_pic_wechat_media_id', max_length=200, null=True, verbose_name='\u66f2\u8c31\u5185\u5bb9\u56fe\u7247\u6240\u5728\u5fae\u4fe1\u670d\u52a1\u5668id'),
        ),
        migrations.AddField(
            model_name='scorewidget',
            name='voice_wechat_media_id',
            field=models.CharField(blank=True, db_column='c_voice_wechat_media_id', max_length=200, null=True, verbose_name='\u66f2\u8c31\u5185\u5bb9\u56fe\u7247\u6240\u5728\u5fae\u4fe1\u670d\u52a1\u5668id'),
        ),
        migrations.AlterField(
            model_name='scorewidget',
            name='type',
            field=models.IntegerField(choices=[(1, b'\xe8\xaf\xad\xe9\x9f\xb3'), (2, b'\xe6\x96\x87\xe5\xad\x97')], db_column='n_type'),
        ),
        migrations.AlterField(
            model_name='scorewidget',
            name='voice_url',
            field=models.FileField(blank=True, db_column='c_voice_url', null=True, storage=core.django_ext.OssThumbStorage(), upload_to=b'', verbose_name='\u8bed\u97f3\u6587\u4ef6\u5730\u5740'),
        ),
    ]
