# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smarttool', '0002_auto_20160614_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorewidget',
            name='date_added',
            field=models.DateTimeField(db_column='d_added', default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
    ]
