# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttool', '0003_scorewidget_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorewidget',
            name='height',
            field=models.DecimalField(db_column='n_height', decimal_places=2, default=1, max_digits=5, verbose_name='\u9ad8\u5ea6'),
        ),
        migrations.AlterField(
            model_name='scorewidget',
            name='width',
            field=models.DecimalField(db_column='n_width', decimal_places=2, default=1, max_digits=5, verbose_name='\u5bbd\u5ea6'),
        ),
    ]
